# Generated by Django 4.2.16 on 2024-10-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a11_project', '0002_rename_uploaded_at_document_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
    ]
