# Generated by Django 4.2.16 on 2024-10-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a11_project', '0003_rename_uploaded_at_uploadedfile_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='projects/'),
        ),
    ]
