# Generated by Django 4.2.16 on 2024-10-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a11_project', '0005_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='projects/'),
        ),
    ]
