# Generated by Django 4.2.16 on 2024-11-15 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a11_project', '0006_alter_document_file'),
    ]

    operations = [

        migrations.AddField(
            model_name='club',
            name='points',
            field=models.IntegerField(default=0),
        )
    ]
