# Generated by Django 4.2.16 on 2024-11-16 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a11_project', '0007_budget_club_points_expenditure_chatmessage'),
    ]

    operations = [

        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        )
    ]
