# Generated by Django 4.2.16 on 2024-11-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a11_project', '0007_budget_expenditure_chatmessage'),
        ('a11_project', '0008_budget_profile_points_expenditure_chatmessage'),
    ]

    operations = [
    ]
