# Generated by Django 4.2.16 on 2024-11-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a11_project', '0010_club_event_event_member_requests_event_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='document',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
