# Generated by Django 4.2.16 on 2024-12-02 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a11_project', '0011_event_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='a11_project.event'),
        ),
    ]
